version: '3.8'

services:
  db:
    container_name: 311-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - target: 5432
        published: ${DB_HOST_PORT}
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    container_name: 311-redis
    restart: always
    build: ./redis
    expose:
      - 6379

  server:
    container_name: 311-server
    build: .
    ports:
      - target: 5000
        published: ${SERVER_HOST_PORT}
    volumes:
      - ./:/app
    depends_on:
      - db
    command: bash -c "python bin/check_setup.py && python app.py"

  adminer:
    container_name: postgres-dashboard
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rebrow:
    container_name: redis-dashboard
    image: marian/rebrow
    links:
      - redis:redis
    ports:
      - 5001:5001

  # jupyter:
  #   container_name: 311-notebook
  #   image: jupyter/scipy-notebook
  #   environment:
  #     DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - ../:/home/jovyan/work

    # frontend:
    #  build:
    #    context: ..
    #  network_mode: host
    #  image: docker.pkg.github.com/hackforla/311-data/frontend:latest
    #  restart: always
    #  container_name: 311-frontend
    #  ports:
    #    - 3000:3000

volumes:
  database:
