version: '3.4'

services:
  db:
    container_name: "311-postgres"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: REDACTED
      POSTGRES_USER: REDACTED
    ports:
      - 5433:5432
    volumes:
      - backend_data:/var/lib/postgresql/data

  redis:
    container_name: "311-redis"
    build:
      context: ../redis
    expose:
      - 6379

  server:
    container_name: "311-server"
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - db
    command: bash -c "python bin/setup.py && python app.py"

  ################ OPTIONAL SERVICES (uncomment to use) ###################

  # adminer:
  #   container_name: "postgres-dashboard"
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  # rebrow:
  #   container_name: "redis-dashboard"
  #   image: marian/rebrow
  #   links:
  #     - redis:redis
  #   ports:
  #     - 5001:5001

  # jupyter:
  #   container_name: "311-notebook"
  #   image: jupyter/scipy-notebook
  #   environment:
  #     DATABASE_URL: postgresql://REDACTED:REDACTED@db:5432/postgres
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - ../:/home/jovyan/work

  ########################## NOT WORKING YET ##############################

  # frontend:
  #  build:
  #    context: ..
  #  network_mode: host
  #  image: docker.pkg.github.com/hackforla/311-data/frontend:latest
  #  restart: always
  #  container_name: "311-frontend"
  #  ports:
  #    - 3000:3000

volumes:
  backend_data:
